### ISSUE TITLE
Use Default and Semigroup?

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/swagger2#1]
Some `Monoid` instances do not obey laws, because `mempty` is used as a default value and is only left identity for `mappend`, but not right (`x <> mempty ≠ x`). For these structures [`Default`](https://hackage.haskell.org/package/data-default/docs/Data-Default.html) and [`Semigroup`](https://hackage.haskell.org/package/semigroups/docs/Data-Semigroup.html) instances might make more sense than `Monoid`:
- `SwaggerInfo`;
- `SwaggerOperation` (can be true `Monoid` if `Bool` is replaced with `Maybe Bool`);
- `SwaggerParameter`;
- `SwaggerParameterOtherSchema`;
- `SwaggerSchema`;
- `SwaggerResponse`;
- `SwaggerExternalDocs`.

**Comment by fizruk** [comment]
@dmjio are you okay with `Default` and `Semigroup` instead of `Monoid`?

**Comment by fizruk** [comment]
With fixed `SwaggerMonoid Text` instance in 10ee930a9b8e43b01f58abda98c2e445dc45fcfd only these are left as not true monoids:

- `SwaggerOperation`;
- `SwaggerParameter`;
- `SwaggerParameterOtherSchema`.

All these probably need `Bool` replaced with `Maybe Bool`.
This will fix `Monoid` instances to obey right identity law and we won't need to introduce `Default`/`Semigroups`.

@dmjio are you okay with `Maybe Bool` in these data types?

**Comment by dmjio** [comment]
`Maybe Bool` is fine
