### ISSUE TITLE
Doc missing from hackage in 2.1.4 release

### ISSUE THREAD

**Issue by mossprescott** [GetShopTV/swagger2#103]
It appears that the docs didn't make it to hackage for the latest release:

http://hackage.haskell.org/package/swagger2-2.1.4

Most of the modules are not linked, and the pages that are there seem to missing stylesheets. Things looked fine in 2.1.3; maybe a bad build?

**Comment by fizruk** [comment]
Yes, doc build failed:

![screen shot 2017-05-03 at 15 37 40](https://cloud.githubusercontent.com/assets/686582/25660792/869343b4-3016-11e7-8ed8-5f03c6f03ed2.png)

I will try to upload docs manually now.

**Comment by phadej** [comment]
Uploaded docs for 2.1.4.1
