### ISSUE TITLE
What about HasEnum for Schema?

### ISSUE THREAD

**Issue by qrilka** [GetShopTV/swagger2#109]
According to https://swagger.io/specification/#schemaObject `enum` is a valid property for any schema object not only for parameters, shouldn't `HasEnum` instance be added for `Schema` too?

**Comment by fizruk** [comment]
Yes!

In all `ParamSchema` properties could be carried over with `HasX` instances to `Schema`.
And also `NamedSchema` :)

Are you willing to make a PR to add all those missing instances?

P.S. You can currently edit `enum` property of any `Schema`, you just have to dig one level deeper, into `paramSchema`.

**Comment by qrilka** [comment]
Actually I think I was looking into wrong direction - I tried to add `enum_` to `Referenced Schema` which of course failed but `Inline $ toSchema (Proxy @ String) & enum_ .~ ["foo", "bar"]` looks to work OK.
As for the instances - it looks like version 2.1.3 (which we currently use) has them but in `master` I see only instance of `HasParamSchema` for `NamedSchema` - did instance for `Schema` disappear during refactoring and needs to be returned back? Or maybe I miss something?

**Comment by fizruk** [comment]
Yeah, I got confused too... instances got merged into a more general one:

```haskell
instance OVERLAPPABLE_ HasParamSchema s (ParamSchema t)
  => HasEnum s (Maybe [Value]) where
```

So anything that has `ParamSchema` also has `enum_` and other lenses.

This is not obvious from haddocks now... I wonder, how can we improve that while not having tons of instances. @phadej do you know of a trick?

**Comment by qrilka** [comment]
And the other tied issue is #103 :)

**Comment by qrilka** [comment]
But otherwise @fizruk feel free to close this issue

**Comment by qrilka** [comment]
Closing as invalid
