### ISSUE TITLE
swagger 2.1.5 not in stackage nightly

### ISSUE THREAD

**Issue by simonmichael** [GetShopTV/swagger2#122]
Just FYI: the latest swagger2 is being kept out of stackage nightly by hledger-api's upper bound on it, cf: https://github.com/fpco/stackage/issues/2861 , https://github.com/simonmichael/hledger/issues/612 . Any help with updating hledger-api to support the new swagger2 (as well as the older ones) is welcome.

**Comment by fizruk** [comment]
Solution presented in https://github.com/simonmichael/hledger/issues/612#issuecomment-330632015.

**Comment by simonmichael** [comment]
hledger master now supports old and new swagger2. I plan to wait for the hledger 1.4 release in about a week, at which time this will be in stackage and the bound on swagger2 can be lifted.

**Comment by simonmichael** [comment]
Resolved sooner, by https://github.com/fpco/stackage/commit/68297c61680e4fc55aa4b65e63d4c2e43b98960b.
