### ISSUE TITLE
2.1.6 haddock docs are formatted strangely and missing modules

### ISSUE THREAD

**Issue by dfithian** [GetShopTV/swagger2#134]
I'm looking [here](http://hackage.haskell.org/package/swagger2), and it's missing docs for many of the exported modules (Data.Swagger in particular).

I'm looking [here](http://hackage.haskell.org/package/swagger2-2.2/docs/Data-Swagger-Internal.html), and it's missing appropriate styling.

**Comment by fizruk** [comment]
I think the haddocks are fixed now.
