### ISSUE TITLE
Dropped from LTS 10 nightly

### ISSUE THREAD

**Issue by NCrashed** [GetShopTV/swagger2#137]
Hi, there are upper bounds problems with `haskell-src-exts` that causes `swagger2` to be deleted from latest stackage (and thus my packages that depends on `swagger2`, heh).

Snoyman post: https://www.snoyman.com/blog/2017/12/dropped-packages-following-lts-10
PR: https://github.com/fpco/stackage/pull/3140/files#diff-b42a893675b90dbfa12fe0ce6064f0baR2105

**Comment by phadej** [comment]
Let's wait till maintainers of aeson-qq add support, i.e. have holiday till next year!

**Comment by fizruk** [comment]
Seems like both `aeson-qq` and `swagger2` are back in LTS and nightly snapshots :)
