### ISSUE TITLE
Provide a `Options -> SchemaOptions`

### ISSUE THREAD

**Issue by reactormonk** [GetShopTV/swagger2#139]
It would be convenient to reuse the `aesonOptions :: Options` defined for deriving the codes in the swagger definition as well, instead of having to write two different schemas.

**Comment by fizruk** [comment]
@reactormonk right, I would call it `fromAesonOptions :: Aeson.Options -> SchemOptions`.
This seems straightforward, would you like to send a PR? :)

**Comment by przemyslawlib-blueveery** [comment]
`grep -r "aesonOptions"; grep -r "fromAesonOptions"; grep -r "Aeson.Options";`
All return no matches. Where those types renamed? Is it already done? (If not, can you provide filename where I could start).

Thx.

**Comment by przemoli** [comment]
`grep -r "aesonOptions";grep -r "fromAesonOptions";grep -r "Aeson.Options";` All find no match.

Was it renamed? Is this issue already solved?
Can you post a filename where I could start reading?

Thx.
