### ISSUE TITLE
Tags shouldn't be sorted

### ISSUE THREAD

**Issue by neongreen** [GetShopTV/swagger2#165]
Currently we have `_swaggerTags :: Set Tag`. As the result, tags in the generated schema are sorted alphabetically. As the result, tools that rely on this order (both Swagger UI and ReDoc) show endpoint groups in an order that doesn't match the order intended by the user.

Or at least I guess so :slightly_smiling_face:

**Comment by phadej** [comment]
@fizruk Should we have InsOrdSet?

**Comment by Martoon-00** [comment]
Let me remind about this issue. Are there plans to switch to keeping tags in `InsOrdSet`?

**Comment by phadej** [comment]
I assigned this to myself, let's make this happen.
