### ISSUE TITLE
Nullary schema should render valid swagger code

### ISSUE THREAD

**Issue by michalrus** [GetShopTV/swagger2#167]
What we’re doing currently returns quite a few errors from the validator (and crashes swagger-codegen etc.):

https://github.com/GetShopTV/swagger2/blob/f42c345e3a2e7467c524678bd6100c56ee6a9a17/src/Data/Swagger/Internal/Schema.hs#L717-L720

```json
{
  "items": [],
  "type": "array"
}
```

E.g. notice that `"items"` must be an object, and they’re an array above.

But this does not, and closely matches Aeson’s `[]` representation of `()` and mixed nullary/non-nullary constructors of a datatype:

```json
{
  "type": "array",
  "items": {},
  "maxItems": 0,
  "example": []
}
```

**Comment by phadej** [comment]
@michalrus Is

```haskell
-- >>> encode $ sketchSchema (1, 2, 3)
-- "{\"example\":[1,2,3],\"items\":{\"type\":\"number\"},\"type\":\"array\"}"
```

correct schema though? I.e. is the empty array the only wrong thing to do?

**Comment by phadej** [comment]
oh sorry, wrong example

correct one:
```haskell
-- >>> encode $ sketchSchema ("Jack", 25)
-- "{\"example\":[\"Jack\",25],\"items\":[{\"type\":\"string\"},{\"type\":\"number\"}],\"type\":\"array\"}"
```

**Comment by fizruk** [comment]
> E.g. notice that "items" must be an object, and they’re an array above.

I think in Swagger 2.0 arrays as `items` were used to represent tuples and I thought empty array would do. Unfortunately I can't find a confirmation of that now :(

OpenAPI 3.0 allows `items` to only be a schema and deals with tuples using `oneOf` (which is not as strong since it does not enforce order and multiplicity). See https://swagger.io/docs/specification/data-models/data-types/ for details.

So yes, apparently, we should use some schema for items (I don't think `{}` is a correct schema in Swagger 2.0, see #164) and enum to specify that only `[]` is a valid value. E.g. something like

```json
{
  "type": "array",
  "items": {"type":"null"},
  "maxItems": 0,
  "example": []
}
```

**Comment by fizruk** [comment]
> I.e. is the empty array the only wrong thing to do?

I'm not sure anymore if Swagger 2.0 allows tuples. I thought it did, but since I introduced `SwaggerItemsArray` a few years back they've changed the spec a couple times, so I don't know anymore.

**Comment by michalrus** [comment]
@phadej your example:

```json
{"example":["Jack",25],"items":[{"type":"string"},{"type":"number"}],"type":"array"}
```
… is not a schema error, but a semantic error, returning: 

```
Semantic error at definitions.X.items
`items` must be an object
```

Semantic errors don’t make the document invalid, for some reason. Also it works well in Swagger-UI.

-------

This one, on the other hand (more/less our current one):

```json
{"example":[],"items":[],"type":"array"}
```

returns:

```
Schema error at definitions['X'].items
should be object

Schema error at definitions['X'].items
should NOT have less than 1 items
limit: 1

Schema error at definitions['X'].items
should match some schema in anyOf
```

and is not valid.

-------

@fizruk this one is valid as well (according to the validator, I don’t know how correct it is w.r.t. spec):
```json
{
  "type": "array",
  "items": {"type":"null"},
  "maxItems": 0,
  "example": []
}
```

**Comment by phadej** [comment]
ok, so if we return that object for an empty `SwaggerItemsArray` things should pass validation?

**Comment by michalrus** [comment]
I think so. =)

**Comment by phadej** [comment]
@michalrus could you make a PR?

**Comment by fizruk** [comment]
> ```
> Schema error at definitions['X'].items
> should NOT have less than 1 items
> limit: 1
> ```

This strongly suggests that I am not delusional and tuples were indeed supported at some point! 😅 

@michalrus let us know if you're willing to make that PR 😊

**Comment by michalrus** [comment]
Sure, I can. =)

So, for an empty `SwaggerItemsArray`, is it this one:

```json
{
  "type": "array",
  "items": {"type":"null"},
  "maxItems": 0,
  "example": []
}
```
… or this one:
```json
{
  "type": "array",
  "items": {},
  "maxItems": 0,
  "example": []
}
```
…?

Neither of these returns a schema nor a semantic error, so they’re both fine.

I like untyped a bit more, since it doesn’t display the `null` in Swagger-UI (in the models section and tabs), but just an empty object instead.

**Comment by phadej** [comment]
:+1: for untyped

**Comment by fizruk** [comment]
@michalrus I'm okay with any one as long as you clearly document the choice. AFAIK the untyped one is not a valid Swagger 2.0 Schema, but it does not matter when there are zero values of that type I guess (lazy typing?) 😅

**Comment by michalrus** [comment]
Okay. =)

Please, take a look at the horrendous draft… … …
