### ISSUE TITLE
New release with optics support

### ISSUE THREAD

**Issue by arybczak** [GetShopTV/swagger2#202]
Can we have a new release now that #200 is merged please?

**Comment by fisx** [comment]
(I'm in favor, but don't have hackage access.)

**Comment by fizruk** [comment]
@arybczak @fisx I will prepare release this weekend, if that's not an urgency.

**Comment by fizruk** [comment]
[`swagger2-2.5` released on Hackage](https://hackage.haskell.org/package/swagger2-2.5)!
