### ISSUE TITLE
Empty paths field omitted from schema

### ISSUE THREAD

**Issue by paulyoung** [GetShopTV/swagger2#209]
According to the Swagger 2 spec, the `paths` field is required, and some tooling considers it to be an error when the field is omitted.

It's possible to generate such JSON using swagger2. I think `"paths": {}` should be emitted in the case where there are no paths.

**Comment by paulyoung** [comment]
I'm currently working around this with:

```haskell
main :: IO ()
main = putStrLn . read . show . encode $ mySwagger
  where
    encode :: Swagger -> LByteString
    encode = Aeson.encode . addPathsField . Aeson.toJSON

    addPathsField :: Aeson.Value -> Aeson.Value
    addPathsField value
      | (Aeson.Object kvs) <- value =
          Aeson.Object $ HashMap.alter (Just . fromMaybe (Aeson.object [])) "paths" kvs
      | otherwise = value
```

**Comment by fisx** [comment]
no, wait, i have something.
