### ISSUE TITLE
Aeson security Issue (Servant dependency)

### ISSUE THREAD

**Issue by akhesaCaro** [GetShopTV/swagger2#226]
Hi swagger2 maintainers,

I am a [servant](https://github.com/haskell-servant/servant) maintainer and I am trying to bump aeson following the [security issue](https://github.com/haskell/aeson/issues/864) 
Servant has a dependency with **swagger2** but [aeson](https://github.com/GetShopTV/swagger2/blob/51f2108826dff2a0c31b581025e8f9f9b29accb1/swagger2.cabal#L76) has been bounded below 1.6

Would it be possible to relax constraint for **aeson** (>= 2.0.0.0)?

**Comment by fizruk** [comment]
Hi, I'm sorry for a late reply, we haven't been very active on the open source front lately. However, @swamp-agr has volunteered to help with this :)
