### ISSUE TITLE
Consider using makeFields, not makeLenses

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/swagger2#39]
`HasParamSchema` will still be useful.

[`makeFields`](https://hackage.haskell.org/package/lens-4.12/docs/Control-Lens-TH.html#v:makeFields) should shorten many names in [`Data.Swagger.Lens`](http://hackage.haskell.org/package/swagger2-1.1.1/docs/Data-Swagger-Lens.html).
For example it would turn this code:

```haskell
swagDoc :: Swagger
swagDoc = toSwagger (Proxy :: Proxy API)
  & info.infoTitle .~ "Todo API"
  & info.infoVersion .~ "1.0"
  & info.infoDescription ?~ "This is an API that tests servant-swagger support for a Todo"
  & info.infoLicense ?~ License "MIT" (Just (URL "http://mit.com"))
```

into

```haskell
swagDoc :: Swagger
swagDoc = toSwagger (Proxy :: Proxy API)
  & info.title .~ "Todo API"
  & info.version .~ "1.0"
  & info.description ?~ "This is an API that tests servant-swagger support for a Todo"
  & info.license ?~ License "MIT" (Just (URL "http://mit.com"))
```

@dmjio what do you think? Would this simplify customizing spec by a significant ammount?

**Comment by dmjio** [comment]
yea, this would be really cool, as long as we don't have any overlapping lenses. In that case it might be best to make a typeclass that contains a lens. (example: if `title` is found in more than one data type)

**Comment by fizruk** [comment]
@dmjio [`makeFields`](https://hackage.haskell.org/package/lens-4.12/docs/Control-Lens-TH.html#v:makeFields) will do exactly that! Check out its documentation :)

**Comment by dmjio** [comment]
oh that's beautiful, for some reason I was thinking of `makeLenses`. Looks perfect
