### ISSUE TITLE
Make NamedSchema a data type

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/swagger2#40]
To cite @jkarni:

> if `NamedSchema` had an instance for `HasParamSchema` (which I guess means it shouldn't be a tuple) that would save me the chars `. _2`, for what it's worth

Having a separate type will also mean `Name` and `Schema` will be named fields rather than `_1` and `_2`.

**Comment by jkarni** [comment]
I'm happy to do this, but `NamedSchema` would have to move (if we want the lenses for it to be in `Lenses.hs`) to avoid circular imports, and I'll defer to you on where to move it to (or whether to have the lenses elsewhere).
