### ISSUE TITLE
ToSchema instances for ByteString

### ISSUE THREAD

**Issue by np** [GetShopTV/swagger2#51]
I'm not quite what these should or actually why `servant-swagger` ends up needing such an instance.
I guess this could be given a similar instance than Text.

**Comment by fizruk** [comment]
@np can you paste the exact error message you are getting? Along with a single API endpoint causing trouble, if possible.

I suppose that you're getting this error for `toSwagger` call, which will demand `ToSchema` instance for `ByteString` only if any of your endpoints accepts (in a `ReqBody`) or responds with a `ByteString`.

Note that `ByteString` does not have a `ToJSON` instance, so it probably makes little sense for it to have `ToSchema` instance.

**Comment by np** [comment]
Ok, let's say I have a wrapper type `T` around a `ByteString`, The type `T` is used as the return value of a `Get` for instance: `Get '[PNG] T`.

What would you recommend as an instance for `ToSchema T` where `T` is such just binary data.

**Comment by fizruk** [comment]
@np Swagger specification offers [a few common formats](http://swagger.io/specification/#dataTypeFormat), among which you can find `byte` (for base64 encoding) and `binary` (for any sequence of octets).

I think the following instance would make sense for `T`:

```haskell
instance ToSchema T where
  declareNamedSchema _ = pure (Just "T", s)
    where
      s = mempty
        & schemaType .~ SwaggerString
        & schemaFormat ?~ "binary"
```

**Comment by fizruk** [comment]
@np [`swagger2-2.01`](http://hackage.haskell.org/package/swagger2-2.0.1) has now [`binarySchema`](http://hackage.haskell.org/package/swagger2-2.0.1/docs/Data-Swagger-Schema.html#v:binarySchema) and [`byteSchema`](http://hackage.haskell.org/package/swagger2-2.0.1/docs/Data-Swagger-Schema.html#v:byteSchema) templates you can use.
E.g. the example above would change to this:

```haskell
instance ToSchema T where
  declareNamedSchema _ = pure (Just "T", binarySchema)
```

I don't think there'll be a `ToSchema ByteString` instance though.

Please reopen this issue if you think it's not resolved.

**Comment by gbaz** [comment]
With a large API we're trying to autogenerate against, having to handwrite a bunch of stuff due to this limitation is a bit annoying. Is a better solution possible? Possibly some sort of parameterization like aeson has with `defaultOptions` so that we could just pass in options that specified the desired schema to use for such things where there's some degree of freedom in the choice?

**Comment by gbaz** [comment]
(Note that the API we're autogenerating against is in turn generated from other code, so its nontrivial to just wrap the bytestrings in the underlying data types ourselves)

**Comment by fizruk** [comment]
@gbaz you can always wrap/replace `ByteStrings` with this simple trick:

```haskell
-- | Replace all occurrences of a type in an API.
-- This will replace response and request body types,
-- but not query parameters, captures or headers.
type family ReplaceInAPI a b api where
  ReplaceInAPI a b (Verb method statusCode contentTypes a) = Verb method statusCode contentTypes b
  ReplaceInAPI a b (ReqBody contentTypes a :> sub) = ReqBody contentTypes b :> ReplaceInAPI a b sub
  ReplaceInAPI a b (param :> sub) = param :> ReplaceInAPI a b sub
```

With this type family you can generate Swagger documentation for an altered API to workaround `ToSchema ByteString` type error:

```haskell
type AlteredAPI = ReplaceInAPI ByteString ArtibraryBinaryData MyAPI

newtype ArbitraryBinaryData = ArbitraryBinaryData ByteString

instance ToSchema ArbitraryBinaryData where
  declareNamedSchema _ = pure (Nothing, binarySchema)

mySwagger :: Swagger
mySwagger = toSwagger (Proxy @AlteredAPI)
```

**Comment by fizruk** [comment]
@gbaz this `ReplaceInAPI` should probably go in [`Servant.API.TypeLevel`](http://hackage.haskell.org/package/servant-0.11/docs/Servant-API-TypeLevel.html) in some form.

**Comment by gbaz** [comment]
This isn't exactly what I'm looking for I think -- the problem is I have a datatype `A` that holds a datatype `B`. And somewhere in `A` and `B` are the bytestrings. So the instance ToSchema for `A` and `B` can't be autogenerated... You can't see the bytestrings at the level of the servant code. There's instead a `Post '[JSON] A` at that level.

**Comment by fizruk** [comment]
@gbaz ah, I see. Sorry for misinterpreting :)

You can do this then in your local code to lift the `ByteString` limitation:

```haskell
-- you need swagger2 internals to override parts of
-- the Generic-based deriving mechanism
import Data.Swagger.Internal.Schema
import GHC.Generics

-- | This orphan instance prevents Generic-based deriving mechanism
-- to use 'ToSchema' 'ByteString' and instead defaults to 'binarySchema'.
instance GToSchema (K1 i ByteString) where
  gdeclareNamedSchema _ _ _ = pure (Nothing, binarySchema)
```

I did not test this code, so let me know if you get stuck.

**Comment by gbaz** [comment]
Nice! it appears to work. Thanks. Maybe both these tricks could be added to the documentation somewhere.

**Comment by phadej** [comment]
@gbaz out of curiosity, how you do define `ToJSON A`

**Comment by gbaz** [comment]
Orphan instances :-)

**Comment by phadej** [comment]
@gbaz, well that's your solution for `swagger2` then :)

**Comment by gbaz** [comment]
Right -- the way to do it as provided above was just somewhat nonobvious to me, as compared to just hand-providing an instance directly. :-)
