### ISSUE TITLE
ToSchema documentation broken

### ISSUE THREAD

**Issue by ivan-m** [GetShopTV/swagger2#60]
It seems that the Haddock documentation for the ToSchema typeclass doesn't seem to match the actual code any more: https://github.com/GetShopTV/swagger2/blob/master/src/Data/Swagger/Internal/Schema.hs#L78

**Comment by fizruk** [comment]
@ivan-m thanks for noticing!

You're right, it should now be this:

```haskell
data Coord = Coord { x :: Double, y :: Double }

instance ToSchema Coord where
  declareNamedSchema = do
     doubleSchema <- declareSchemaRef (Proxy :: Proxy Double)
     return $ NamedSchema (Just "Coord")) $ mempty
       & type_ .~ SwaggerObject
       & properties .~
           [ ("x", doubleSchema)
           , ("y", doubleSchema)
           ]
       & required .~ [ "x", "y" ]
```

I'll update the docs on Hackage shortly!
