### ISSUE TITLE
ToSchema for Data.Aeson.Value generates invalid json

### ISSUE THREAD

**Issue by alanz** [GetShopTV/swagger2#62]
When using

``` haskell
deriving instance Generic Value
instance ToSchema Value
```

via `declareResponse` the generated json is

``` json
  "definitions": {
    "Value": {
      "minProperties": 1,
      "maxProperties": 1,
      "type": "object",
      "properties": {
        "String": {
          "type": "string"
        },
        "Null": {
          "items": [],
          "type": "array"
        },
        "Array": {
          "items": {
            "$ref": "#/definitions/Value"
          },
          "type": "array"
        },
        "Object": {
          "additionalProperties": {
            "$ref": "#/definitions/Value"
          },
          "type": "object"
        },
        "Number": {
          "type": "number"
        },
        "Bool": {
          "type": "boolean"
        }
      }
    },
  }
```

This fails to validate when the entire swagger.json file is lloaded into http://editor.swagger.io/#/, complaining about the "Null" definition as 

```
✖ Swagger Error

Not a valid schema items definition
Jump to line 31
Details
Object
code: "ANY_OF_MISSING"
message: "Not a valid schema items definition"
path: Array [5]
inner: Array [2]
level: 900
type: "Swagger Error"
description: "Not a valid schema items definition"
lineNumber: 31
```

I presume this is because `items` is an empty list for `Null`

**Comment by alanz** [comment]
Odd, http://spacetelescope.github.io/understanding-json-schema/reference/array.html#list-validation says "The empty array is always valid:"

**Comment by fizruk** [comment]
Unfortunately, this is how things are.

Swagger spec does not tell anything about `items` being a non-empty list, but it does tell us that `items` is required. In general `items` is an object/reference for homogenous arrays and an array for encoding tuples. So using `items: []` for encoding `Null` seems reasonable (note that this is also how `aeson` would actually encode `Null` when using generic derivation).

Previously I've also tried using `enum: [[]]`, but that also gets an error.

It seems that both `swagger-editor` and `swagger-ui` do not perfectly obey Swagger spec.

We might get around that with `{"type": "array", "items": [{"type": "null"}], "maxItems": 0}`, but it seems arbitrary and not useful.

BTW, do you actually want a `ToSchema` instance for `Value` that does not correspond to its `ToJSON` instance?

**Comment by alanz** [comment]
My goal is to get to the point where the standard swagger tools, mainly `swagger-ui` and the code gen work with the haskell-ide-engine servant API.

I am new to this ecosystem, so I do not know what the appropriate approach is.

Perhaps the best point of attack would be to get the swagger tool validation fixed?

**Comment by fizruk** [comment]
@alanz does that error prevent you from displaying the API?

Note that some errors are actually warnings — they do not affect the UI or affect it negligibly.
Also note that `swagger-ui` is a bit older than `swagger-editor` and as such supports fewer features of Swagger.

**Comment by alanz** [comment]
I have only been using the `swagger-editor` so far, as I get my api generator to work. I will ignore this problem for now, and try the other tools when I am happy with the rest of my generated `swagger.json`

**Comment by fizruk** [comment]
@alanz I'm still interested in your answer to this question, if you don't mind :)

> BTW, do you actually want a ToSchema instance for Value that does not correspond to its ToJSON instance?

Note that `swagger2` does not provide an instance for `Value` because Swagger Schema does not allow ambiguous or undefined type and does not provide `anyOf` property like JSON Schema does.
So it is impossible to provide a valid `ToSchema Value` instance matching `ToJSON`.

**Comment by alanz** [comment]
I think the problem only comes into play for the JSON Null value. I am not sure how much this is used in practice for APIs.

And it originates because some `hie` commands are specified as returning an aeson `Object` rather than a full type.

It might be better to sidestep the issue and let the `Object` be encoded directly as JSON, rather than an encoding of the aeson `Value` item.

**Comment by fizruk** [comment]
If you're only interested in returning arbitrary `Object`, you can specify only the type and leave other `Schema` properties undefined:

```haskell
objectSchema :: Schema
objectSchema = mempty & type_ .~ SwaggerObject
```

Note however that `Data.Aeson.Object` is a type synonym for `HashMap Text Value`.
So you might want to wrap it into a `newtype` to define a separate `ToSchema` instance.

**Comment by alanz** [comment]
Ok, will give it a try

**Comment by alanz** [comment]
@fizruk wrt the the `Null` encoding for a `Value`.  Consulting the spec and experimenting in the editor it seems that

```yaml
      'Null':
        enum: ["Null"]
```

works. This ties up with my intuition that `Value` is a sum type, and we just need a constant marker for its presence.  I think the problem comes from that we actually have two levels of encoding (three, if you include the `Aeson.encode` function), where we have a JSON structure represented as a `Value`, which we in turn encode in JSON. But not via `encode`, we want to reconstruct the `Value`.  In the HIE case anyway.

It is a moot point whether this is the right thing to do at all.

**Comment by fizruk** [comment]
Closing in favour of #86.
