### ISSUE TITLE
Record style data declarations generate better swagger

### ISSUE THREAD

**Issue by alanz** [GetShopTV/swagger2#63]
This is not a bug, just an observation, which should perhaps be documented.

The generically-derived swagger schema for

``` haskell
data Pos = Pos Line Col
```

generates

``` json
    "Pos": {
      "items": [
        {
          "$ref": "#/definitions/Line"
        },
        {
          "$ref": "#/definitions/Col"
        }
      ],
      "type": "array"
    },
```

whereas

``` haskell
data Pos = Pos {line:: Line,col:: Col}
```

generates

``` json
    "Pos": {
      "required": [
        "line",
        "col"
      ],
      "type": "object",
      "properties": {
        "line": {
          "$ref": "#/definitions/Line"
        },
        "col": {
          "$ref": "#/definitions/Col"
        }
      }
    },
```

**Comment by fizruk** [comment]
This is sort of documented in

> [`ToSchema`'s] corresponding value-encoding class is `ToJSON` (from `aeson` package).

But I agree that we could be more explicit about default encoding for different data types.

**Comment by alanz** [comment]
I think the problem is that the `item` based encoding does not mark both items as being required, too.

**Comment by fizruk** [comment]
@alanz yes, we should add `minItems`/`maxItems` for tuples, thanks for pointing that out!

**Comment by fizruk** [comment]
Still have to add `minItems`/`maxItems` for array-encoded tuples. This should be done in [`withFieldSchema`](https://github.com/GetShopTV/swagger2/blob/master/src/Data/Swagger/Internal/Schema.hs#L686-L687) to increment `minItems` and `maxItems`.
