### ISSUE TITLE
The pathitems should be sorted in the generated swagger.json

### ISSUE THREAD

**Issue by alanz** [GetShopTV/swagger2#64]
The pathitems are stored in a `HashMap`, and so come out in random order when serialised to JSON.

These should be sorted, otherwise introspection tools struggle with them.

**Comment by alanz** [comment]
Thinking about it, there may be a specific ordering that makes sense in terms of presentation/understanding of an API. 

So maybe an ordered list should be used rather than a `HashMap`, so the user can manage the order.

**Comment by fizruk** [comment]
This has already been addressed in #56 with an introduction of `InsOrdHashMap` (which keeps elements in order of insertion). Feel free to reopen if it does not solve your problem though.

**Comment by alanz** [comment]
Ok, I am using the hackage (via stackage) version, I do not think this
feature has been published there yet.
