### ISSUE TITLE
example for decoding Swagger 2.0 API specifications or manipulating them.

### ISSUE THREAD

**Issue by joe9** [GetShopTV/swagger2#68]
> This library is inteded to be used for decoding and encoding Swagger 2.0 API specifications as well as manipulating them.

I could not find anything in the examples directory to figure out how to decode or manipulate Swagger API definition. Can you please help?

I have a Swagger schema from which I generated haskell code using swagger-codegen. Unfortunately, I am not happy with the generated code and I am not proficient enough in Java to fix it. Hence, wanted to check if there was any way I can read the Swagger schema using haskell.

**Comment by phadej** [comment]
Doesn't using `aeson` work for you?

```hs
contents <- BS.readFile "swagger.json"
schema <- decode contents :: IO Swagger  -- Data.Aeson.Compat.decode
print schema
```

**Comment by fizruk** [comment]
To decode Swagger specification or any of its parts you just use `FromJSON` instance.
For example, you can do this:

```haskell
import Data.Aeson (eitherDecode)
import qualified Data.ByteString.Lazy.Char8 as BL8
import Data.Swagger (Swagger)

readSwaggerSpec :: FilePath -> Either String Swagger
readSwaggerSpec = eitherDecode <$> BL8.readFile path
```

Something similar is used in [`servant-swagger`'s example test suite](https://github.com/haskell-servant/servant-swagger/blob/master/example/test/TodoSpec.hs#L21) to check that generated API spec corresponds to `swagger.json` (to track API changes).

To manipulate `Swagger` the most convenient way is to use [lenses and prisms](https://www.stackage.org/haddock/lts-6.9/swagger2-2.0.2/Data-Swagger.html#g:3). There examples demonstrate how to change/build spec with lenses, but you can also use lenses to query any part, e.g.:

```haskell
spec ^.. allOperations  -- get a list of all 'Operation's mentioned in the spec
```

**Comment by joe9** [comment]
Thanks.
