### ISSUE TITLE
Changes introduced by aeson-1

### ISSUE THREAD

**Issue by phadej** [GetShopTV/swagger2#69]
I'm not sure if we should take them into account. At least how `Map` and `HashMap` can be serialised in `aeson-1`.

Please discuss.

**Comment by fizruk** [comment]
We should change these `ToSchema` instances:

```haskell
instance ToSchema a => ToSchema (Map T.Text  a)
instance ToSchema a => ToSchema (Map TL.Text a)

instance ToSchema a => ToSchema (HashMap String  a)
instance ToSchema a => ToSchema (HashMap T.Text  a)
instance ToSchema a => ToSchema (HashMap TL.Text a)
```

To do that we have to either introduce a new `ToSchemaKey` class corresponding to `ToJSONKey`, or to use `ToParamSchema`. I am not sure which we should use.

The rest of the changes we can probably safely ignore.

**Comment by phadej** [comment]
From `ToJSONKey` we'll know whether `Map` is serialised as object or array,
I'm not sure whether swagger spec supports specifying what kind the keys are in `Dict<key,value`? So this is almost correct:
```hs
instance (ToJSONKey k, ToSchema a) => ToSchema (Map k a) where
  declareNamedSchema _ | isObjectEncoding (Proxy :: Proxy k) = do
    schema <- declareSchemaRef (Proxy :: Proxy a)
    return $ unnamed $ mempty
      & type_ .~ SwaggerObject
      & additionalProperties ?~ schema
  where
    isObjectEncoding p = ...
```

**Comment by fizruk** [comment]
Hmm, you're right, `toJSONKey` provides all necessary info:

```haskell
instance (ToJSONKey k, ToSchema a) => ToSchema (Map k a) where
  declareNamedSchema _ = case toJSONKey :: ToJSONKeyFunction a of
    ToJSONKeyText  _ _ -> declareObjectMapSchema
    ToJSONKeyValue _ _ -> declareNamedSchema (Proxy :: Proxy [(k, a)])
  where
    declareObjectMapSchema = do
      schema <- declareSchemaRef (Proxy :: Proxy a)
      return $ unnamed $ mempty
        & type_ .~ SwaggerObject
        & additionalProperties ?~ schema
```

**Comment by fizruk** [comment]
@phadej do we need to address any of the other changes `aeson-1.0.0.0` introduced?

**Comment by fizruk** [comment]
Hmm, that instance above requires also `ToSchema k` which is only used for array representation, but I guess that's not a problem.
