### ISSUE TITLE
Enforce swagger spec properties

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/swagger2#7]
Some properties are optional/required depending on values of other properties.
It would be good to be able to enforce this relations in our data model.

One way to do this is to encode it as sum-of-products with multiple duplication of fields for every combination of properties that influence the form of the whole object. Then we might provide a lens-like interface so that users won't be dependant on that tricky internal representation of swagger spec.

Another approach might be to use limited form of dependent type hackery. E.g. like this:

```haskell
-- | Type-level case.
type family Case (x :: k) (xs :: [(k, r)]) (def :: r) where
  Case _x [] def = def
  Case x ((x, r) : _xs) _def = r
  Case x (_p : xs) def = Case x xs def

type When x y ty = Case x [(y, ty)] Void
type Unless x y ty = Case x [(y, Void)] ty

-- loc determines parameter location (e.g. "body", "query", etc.)
data Param loc = Param
  {  -- this property is only for "body" parameters
    paramSchema :: When loc InBody Schema

  ,  -- this property is only for non-"body" parameters
    paramType :: Unless loc InBody ParamType
  , ... }

data Items ty = Items
  { itemsCollectionFormat :: When ty TyArray CollectionFormat
  , ... }
```

This can result in a cleaner and easier to comprehend model, but there might be some problems with deriving generic instances (we might just have a separate generic instance for every combination of type parameters, not that bad actually).

**Comment by fizruk** [comment]
I have been thinking about this occasionally and tried a few things.
So far it looks like it's not worth pursuing this sort of specification model.

My related work can be found [in this gist](https://gist.github.com/fizruk/f82fbabb229eb0e2aa92).
This is a partial solution to the problem with the main idea to have two models: "typed" and "untyped" (or rather "undertyped"). Having "untyped" model solves issues with common instances (e.g. `ToJSON`, `FromJSON`). Most of the connections between "typed" and "untyped" model can be solved with TH generation (you can even derive the whole "untyped" model from "typed" one, although I haven't yet completed derivation mechanism).

One nice thing about that gist is that any `model` has a `Valid model model` instance.
This enables user to optionally use the "untyped" model directly.
It might be useful to tweak existing `Some (Valid model)` without having to `dispatch` (*if you know what you're doing*, of course).

I think this "type and TH sorcery" can be made into a separate library, completed and be used for "more typed" models... but it kinda feels wrong.

Perhaps what I am trying to do is to use dependent types in a language without such.
Or maybe dependent types won't help either.

@dmjio what do you think about all this?

**Comment by dmjio** [comment]
@fizruk, I tend to agree. While noble, adding TH and families to enforce invariants on the oft ill-defined spec. may be more trouble than it's worth. I think viewing this library as our "assembly" and having higher level libraries compile to it (via GHC.Generics / TH) is the way to go. If you're pleased with the state of this library as a swagger assembly language, then I think it's time migrate servant swagger over. Once that's done we can generically infer models there. Since inference of swagger models can come from both the 'Rep' type and the swagger type level specification we might need a custom generic deriving for just servant-swagger. Although im not opposed to a separate "swagger deriving" package

**Comment by fizruk** [comment]
I am okay with the state of this library, so you can start migrating `servant-swagger`.

I guess I can start working on generic schema derivation within this library.
Although you're right that we'll most likely need a separate generic derivation for `servant-swagger`, I think many things would be reused rather than reimplemented.

**Comment by fizruk** [comment]
For the sake of history:

Some code redundancy regarding types and collection formats has been removed with `SwaggerType` (f9c8629d780d625e4d7e33c843ff0aaba78a15aa) and `CollectionFormat` GADTs (a9cdd0f9e1d55795eab99cd83c7671bf770db732).

Although this does not enforce anything that hasn't been enforced already, it makes "untyped" swagger model considerably simpler.

I am closing this until we have some new ideas/instruments.
