### ISSUE TITLE
'mixed' sum types generate bad swagger json

### ISSUE THREAD

**Issue by agrafix** [GetShopTV/swagger2#74]
Given code like this:

``` haskell
data PatRowStatus
    = PatRowValid !PatRow
    | PatRowConflict
    deriving (Show, Eq, Ord, Generic, Typeable)

instance ToSchema PatRowStatus
```

a bad `swagger.json` will be generated:

```
✖ Swagger Error
Not a valid response definition
Jump to line 154
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 49
Details
 Object
```

The lines are (marked with `<<< ERROR HERE`):

```
  PatRowStatus:
    minProperties: 1
    maxProperties: 1
    type: object
    description: Status of a patient record
    properties:
      PatRowConflict: <<< ERROR HERE
        items: []
        type: array
      PatRowValid:
        $ref: '#/definitions/PatRow'
```

and 

```
  '/api/patient/{ipid}':
    get:
      responses:
        '200': <<< ERROR HERE
          schema:
            $ref: '#/definitions/PatRowStatus'
          description: ''
        '404':
          description: '`ipid` not found'
      produces:
        - application/json
      parameters:
        - required: true
          in: path
          name: ipid
          type: string
```

If I add at least one field to each constructor, or each field does not have any constructors all works fine. It's probably not clear what the swagger documentation would look like?

**Comment by fizruk** [comment]
The first error is known to me and unfortunately I don't think we can fix it. More specifically, the error is about `items: []` which Swagger don't like. However, AFAIK it does not contradict Swagger specification.

The second error I'm not sure about. Is there any message for it?

**Comment by agrafix** [comment]
I think the second error is due to the first error, i.e. swagger (or in this case the swagger editor at http://editor.swagger.io/#/ ) fails to read the `PatRowStatus` definition thus the API endpoint is falsy. 

I'm also unsure how to fix it, but maybe we can document somewhere that this won't work out?

**Comment by fizruk** [comment]
Yes, I guess we should add a section about known validation errors.
Contributions are welcome! :)

**Comment by agrafix** [comment]
I'll give it a shot

**Comment by fizruk** [comment]
Closed by #83.

**Comment by vwwv** [comment]
@fizruk, would a PR constraining the shape allowed to be generic derived to those not problematic ones be welcome ?
Also using like https://downloads.haskell.org/~ghc/master/users-guide/glasgow_exts.html#custom-compile-time-errors to explain the issue ?

**Comment by fizruk** [comment]
Yes, it would! I have used custom type errors to prevent people from making an instance for ByteString and here we can use that too.

Although in this case I'm not sure it's easy to separate problematic shapes. If it's not I wish we had custom type warnings.

Anyway, work in this area would be appreciated and might be useful for servant-docs and similar libraries as well.

**Comment by vwwv** [comment]
Ok, I'll give it a try this week :)
