### ISSUE TITLE
Generic deriving doesn't nest

### ISSUE THREAD

**Issue by parsonsmatt** [GetShopTV/swagger2#80]
Deriving a generic implementation of a data type only considers the top level generic derivation and requires `ToSchema` instances of all data types contained therein, rather than just `Generic` instances.

Suppose I have a type `Foo` in a library that I want an instance of `ToSchema` for:

```haskell
module Whatever where

data Foo = Foo { bar :: Bar }
    deriving Generic

data Bar = Bar deriving Generic
```

In my own code, I'd write:

```haskell
newtype MyFoo = MyFoo Foo
    deriving Generic

instance ToSchema MyFoo
```

The code now is going to complain that `Foo` doesn't have a `ToSchema` instance. So instead I can do:

```haskell
instance ToSchema MyFoo where
    declareNamedSchema _ = genericDeclareNamedSchema defaultSchemaOptions (Proxy :: Proxy Foo)
```

which works for `Foo`, but complains about `Bar`.

Ideally, the generic derivation should use the `Generic` machinery all the way down.

**Comment by phadej** [comment]
Don't you write
```hs
-- probably in Whatever module
instance ToJSON Bar
instance ToJSON Foo
-- in your code
instance ToJSON MyFoo
```

So there are no way around than writing:
```hs
instance ToSchema Bar
instance ToSchema Foo
instance ToSchema MyFoo
```

Unfortunately you might end up with orphan instances, so without knowing what actual `Bar` and `Foo` are, I cannot comment on them further.

**Comment by parsonsmatt** [comment]
That's fair. Do you know off hand if there's a reason that the generic instance doesn't fallback to generic if `ToSchema` or `ToJSON` aren't found?

**Comment by phadej** [comment]
@parsonsmatt because you cannot write code "If there is instance `MyClass a` do this, otherwise do that". 

I can found the [related SO question](http://stackoverflow.com/questions/26885067/why-context-is-not-considered-when-selecting-typeclass-instance-in-haskell), but without a good answer. I'll try to think of one.
