### ISSUE TITLE
Can't parse Azure API specifications

### ISSUE THREAD

**Issue by lostman** [GetShopTV/swagger2#89]
I'm trying to parse Azure API specifications:

https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-storage/2016-05-01/swagger/storage.json

```
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedLists #-}

import qualified Data.Aeson as Aeson
import qualified Data.ByteString.Lazy as BL
import           Control.Lens
import           Data.Swagger

main = do
    bs <- BL.readFile "azure-rest-api-specs/arm-storage/2016-05-01/swagger/storage.json"
    case Aeson.eitherDecode bs :: Either String Swagger of
        Left err -> error err
        Right s -> print s
```

But I'm getting an error:
```
Error in $.definitions: failed to parse field definitions: key "type" not present
```
An example from `"definitions"` looks like this:
```
  "definitions": {
    "StorageAccountCheckNameAvailabilityParameters": {
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": [ "Microsoft.Storage/storageAccounts" ]
        }
      },
      "required": [
        "name",
        "type"
      ],
      "description": "The parameters used to check the availabity of the storage account name."
    }
  }
```
Is there a way to deal with this?

**Comment by fizruk** [comment]
The problem is `StorageAccountCheckNameAvailabilityParameters` is missing `"type"` key.
I suspect they assume `"object"` type by default, so you can insert missing type before parsing Swagger spec. However, I believe Swagger 2.0 specification demands `"type"` to always be present.

I would recommend using [`aeson-lens`](https://hackage.haskell.org/package/lens-aeson-1.0.0.5/docs/Data-Aeson-Lens.html) to fix the spec before parsing it:

```haskell
-- | This will fix the spec by adding @"object"@ type if there is none.
fixSwaggerJSON :: Value -> Value
fixSwaggerJSON json = json
  & key "definitions" . traverse . _Object . at "type" %~ fromMaybe "object"
```

**Comment by lostman** [comment]
Thanks! Adding `"type": "object"` helped. I only tried parsing `storage.json` for now. I also had a similar issue with `allOf` field:
```
failed to parse field definitions: failed to parse field allOf: key "type" not present
```
and adding `"type": "object"` fixed that too.

**Comment by fizruk** [comment]
@lostman can this issue be closed?

**Comment by lostman** [comment]
Yes. Thanks for help!
