### ISSUE TITLE
No instance for (Data.Swagger.Internal.ParamSchema.GToParamSchema

### ISSUE THREAD

**Issue by YPares** [GetShopTV/swagger2#90]
Following the example in http://hackage.haskell.org/package/swagger2-2.1.3/docs/Data-Swagger.html I'm trying to make Person an instance of ToParamSchema (I have an API where similar datatypes are used to encode query string parameters):

```
import GHC.Generics
import Data.Swagger

data Person = Person { name :: String, age :: Integer } deriving Generic
instance ToParamSchema Person
```

However I'm getting this error everytime the datatype I try to make an instance of ToParamSchema out of is a record:

```
• No instance for (Data.Swagger.Internal.ParamSchema.GToParamSchema
                             (M1
                                C
                                ('MetaCons "Person" 'PrefixI 'True)
                                (S1
                                   ('MetaSel
                                      ('Just "name")
                                      'NoSourceUnpackedness
                                      'NoSourceStrictness
                                      'DecidedLazy)
                                   (Rec0 String)
                                 :*: S1
                                       ('MetaSel
                                          ('Just "age")
                                          'NoSourceUnpackedness
                                          'NoSourceStrictness
                                          'DecidedLazy)
                                       (Rec0 Integer))))
            arising from a use of ‘Data.Swagger.Internal.ParamSchema.$dmtoParamSchema’
        • In the expression:
            Data.Swagger.Internal.ParamSchema.$dmtoParamSchema
          In an equation for ‘toParamSchema’:
              toParamSchema = Data.Swagger.Internal.ParamSchema.$dmtoParamSchema
          In the instance declaration for ‘ToParamSchema Person’
```

**Comment by fizruk** [comment]
@YPares `ParamSchema` deriving does not work for product types and it usually makes little sense. `ParamSchema` is a schema for your query params and captures, and there usually is just one value, not a structure. Do you really need `ToParamSchema` for your type? Or did you just want `ToSchema`? The last one is used for request and response bodies (typically in JSON format).

The error message could be cleaner though with recent GHC 8 custom type errors.

**Comment by YPares** [comment]
@fizruk Actually yes, I do need ToParamSchema because such a type is used to contain the query string parameters (in Servant).

```
type PersonGetStuff  = Session                
                :> Person
                :> Get '[JSON] Stuff
```

**Comment by fizruk** [comment]
@YPares this does not look like a valid Servant API, unless you have custom `HasServer (Person :> api)` instance (as well as custom `HasSwagger (Persion :> api)` instance). Also, since`Person` is a set of query params, not a single parameter, it's not `Person` that needs to have `ToParamSchema` instance, but it's field types.

Can you please share a minimal working example where you either get an error about missing `ToParamSchema` instance or where you just don't have swagger in play?

**Comment by YPares** [comment]
@fizruk Ha, you're right, `HasServer (Person :> api)` was declared somewhere. I'm not a Servant expert, sorry, I missed that much.

**Comment by fizruk** [comment]
@YPares do you still have problems with Swagger or can this be closed?

**Comment by fizruk** [comment]
I am closing this issue. Feel free to reopen if there are any further problems!
