### ISSUE TITLE
Enum values ordering depends on Int

### ISSUE THREAD

**Issue by fizruk** [GetShopTV/swagger2#97]
Turns out `swagger.json` can differ for you if your `Int` is different. On most machines today `Int` is equivalent to `Int64`, but on some it's `Int32`. Having different `Int` results in different `HashMap`, because apparently hashes depend on `Int`. We don't use `HashMap` however, we use [`InsOrdHashMap`](http://hackage.haskell.org/package/insert-ordered-containers-0.2.0.0/docs/Data-HashMap-Strict-InsOrd.html).

For enums [we use `ifolded.asIndex`](https://github.com/GetShopTV/swagger2/blob/master/src/Data/Swagger/Internal/Schema.hs#L726) which uses `FoldableWithIndex` instance of `InsOrdHashMap`.
And that instance currently does not preserve insertion order (see https://github.com/phadej/insert-ordered-containers/issues/12).

Now we can wait for an upstream fix or we can implement `ifolded.asIndex` using `map fst . toList`.

**Comment by phadej** [comment]
`insert-ordered-containers` updated. Should we bump the lower-bound for it, or just let it be?

**Comment by fizruk** [comment]
I confirm that the downstream issue we had with this at work is now (partially) resolved.

I think we just let it be the latest Stackage snapshots already include your changes, so we're fine.
